Create GCD(Euclidean Algorithm)
technojam/Ultimate_Algorithms_Repository pull request #86
Opened 2020-10-01 13:57 UTC by Bijoy-007

Please review

2020-10-02 02:21 UTC, Bijoy-007 commented
@shreyanshdeep @danishjamal104 please review

2020-10-02 21:11 UTC, Rishabhkapoor commented
Hey @Bijoy-007 , Please create an issue before making a PR. You can make use of the template we have created for the same.

2020-10-03 06:48 UTC, Bijoy-007 commented
@Rishabhkapoor Please have a look on #17

2020-10-03 06:49 UTC, Bijoy-007 commented
@Rishabhkapoor I have opened #17 3 days before and I was also assigned for this one please have a look

2020-10-03 07:34 UTC, Rishabhkapoor commented
@Bijoy-007, Kindly always mention the issue for which you are making a PR.

2020-10-03 07:36 UTC, Rishabhkapoor approved these changes

2020-10-03 07:47 UTC, Bijoy-007 commented
@Rishabhkapoor I am very sorry.
I'll mention always

2020-10-03 07:57 UTC, danishjamal104 commented on Basic Algorithms/GCD(Euclidean Algorithm)
> +	GCD gcd1;
Call the GCD function instead of instantiating the GCD class.

2020-10-03 07:57 UTC, danishjamal104 commented on Basic Algorithms/GCD(Euclidean Algorithm)
> +class GCD {
No need to declare a class for GCD, simply declare the function GCD and call it recursively with current edge cases and considering the complexities.

2020-10-03 08:11 UTC, danishjamal104 requested changes
### Changes
1. Delete the GCD class and declare a function instead.
2. In the main function remove object declaration and use the above-declared function.

2020-10-03 08:13 UTC, Bijoy-007 commented
Ok please give me 10mins

2020-10-03 08:18 UTC, Bijoy-007 commented
Review please

2020-10-04 05:40 UTC, Bijoy-007 commented
@danishjamal104  please review

2020-10-06 20:44 UTC, shreyanshdeep approved these changes

2020-10-06 20:44 UTC, merged